messages/urls.py
from django.conf.urls import patterns, include, url
from messages import views

urlpatterns = patterns('',
    url(r'^$', views.messages, name='messages'),
    url(r'^new/$', views.new_message, name='new_message'),
    url(r'^receive_message/$', views.receive_message, name='receive_message'),
)

news/urls.py
from django.conf.urls import patterns, include, url
from news import views

urlpatterns = patterns('',
    # Redirect to news/0/ ... last 10 news
    url(r'^$', views.news0_redirect, name='news0Redirect'),
    url(r'^(?P<start_id>\d+)/$', views.news, name='news'),
    url(r'^newsFromList/(?P<new_db_id>\d+)/$', views.newsFromList, name='newsFromList'),
    #url(r'^news/$', views.news, name='news'),    
    #url(r'^(?P<start_id>\d+)/news_obr1_detail/(?P<new_id>\d+)/$', views.obr1_detail, name='obr1_detail'),
    #url(r'^(?P<start_id>\d+)/news_obr2_detail/(?P<new_id>\d+)/$', views.obr2_detail, name='obr2_detail'),
    #url(r'^(?P<start_id>\d+)/news_obr3_detail/(?P<new_id>\d+)/$', views.obr3_detail, name='obr3_detail'),
    #url(r'^(?P<start_id>\d+)/news_obr4_detail/(?P<new_id>\d+)/$', views.obr4_detail, name='obr4_detail'),
    url(r'^(?P<start_id>\d+)/news_obr_detail/(?P<new_id>\d+)/(?P<obr_id>\d+)/$', views.obr_detail, name='obr_detail'),
    url(r'^pictureOfWeekDetail/(?P<picture_id>\d+)/$', views.picture_of_day_detail, name='picture_of_week_detail'),
    url(r'^info/$', views.info, name='info'),
    url(r'^kontakt/$', views.kontakt, name='kontakt'),
    url(r'^newsList/$', views.newsList, name='newsList'),
)

project_mysites/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static

from news import views

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'project_mysites.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('news.urls', namespace="news")),
    url(r'^messages/', include('messages.urls', namespace="messages")),
    #url(r'^article/', include('article.urls', namespace="article")),
    url(r'^underConstruction/', views.underConstruction, name='underConstruction'),
    url(r'^design/', views.designTest, name='designTest'),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

templates/designTest/designTest.html
<!doctype HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN"> 

<html>
<head>
<!-- <META HTTP-EQUIV="Content-Type" content="text/html; charset=windows-1250"> -->
<META HTTP-EQUIV="Content-Type" content="text/html; charset=ISO 8859-2"> 

 <title>Brouk personal info</title><!doctype HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN"> 

 <META NAME="description" CONTENT="Personal pages about climbing traveling, actual issues and different technical projects.">
 <META NAME="keywords" CONTENT="Michal Broucek, traveling, climbing, Broucek personal projects, SW development, Michal Brouček, cestování, lezení, Brouček vlastní projekty, SW vývoj">
 <META NAME="author" CONTENT="Michal Broucek">

 {% load staticfiles %}
 <link rel="stylesheet" type="text/css" href="{% static 'css/base_design.css' %}" />

</head>

<!-- Page itself -->
<body>
<div id="wrappage" class="wrappage">

  <!-- Head line - pictures and links -->
  <div id="header" class="header" style="position: relative; height: 140px; width: 100%; top: 0%; left: 0%; z-index: 1;">
    {% block header %}
      <img src="../../static/images/header_1280_01.jpg" style="position: relative; top: 0px; left: 0px; z-index: -1;">	
      
      <div id="mytitle" style="position: absolute; top: 20px; left: 80px; z-index: 1;">
        <font style="font-size: small" color="gray">Osobní info stránka:</font> <font style="font-size: 22px;" color="gray"><b>Michal Brouček</b></font>
      </div>
    {% endblock %}
  </div>


  <!-- Odkazy v liste pod hlavickou -->
  <div id="linksidebar" class="linksidebar" style="position: relative; height: 20px; width: 100%; top: 0px; left: 0%; z-index: 1; font-size: small">
    {% block linksidebar %}
      <div id="link1" style="position: absolute; left: 1%; top: 0%">
        <a href="{% url 'news:info' %}">Info</a> <!-- Info proc tyhle stranky ... pokus s Djangem -->
      </div>
      <div id="link1" style="position: absolute; left: 15%; top: 0%">
        <a href="{% url 'underConstruction' %}">Oblíbené odkazy</a>
      </div>
      <div id="link1" style="position: absolute; left: 30%; top: 0%">
        <a href="http://horooddil.zcu.cz">HO USK Plzeň</a>
      </div>
      <div id="link1" style="position: absolute; left: 45%; top: 0%">
        <a href="http://www.hokn.cz">HOKN</a>
      </div>
      <div id="link1" style="position: absolute; left: 60%; top: 0%">
        <a href="http://rocknwall.cz">R&W Plzeň</a>
      </div>
      <div id="link1" style="position: absolute; left: 75%; top: 0%">
        <a href="http://www.honzatrava.cz">Tráva</a>
      </div>
      <div id="link1" style="position: absolute; right: 1%; top: 0%">
        <a href="{% url 'news:kontakt' %}">Kontakt</a>
      </div>
    {% endblock %}
  </div>

  <!-- Left sidebar center content and rightsidebar in main section-->
  <div id="centercontent" class="centercontent" style="position: relative; top: 0px; left: 0px; width: 100%; height: 80%; overflow: auto;">
    {% block centercontent %}
      <p>CENTER CONTENT</p>
    {% endblock %}
  </div>

  <!-- Footer -->
  <div id="footer" class="footer" style="position: relative; height: 15px; width: 100%; left: 0%; font-size: small">
    {% block footer %}
      <div id="footerleft" style="position: absolute; left: 1%; top: 0%">
        <a href="{% url 'news:info' %}">Info</a> stránky na zkoušku
      </div>
      <div id="footercenter" style="position: absolute; left: 45%; top: 0%">
        @autor: <a href="mailto: michalbroucek@seznam.cz?subject=Vzkaz z: mbrouk.cz">Michal Brouček</a>
      </div>
      <div id="footright" style="position: absolute; right: 1%; top: 0%">
	Web framework: <a href="">Django</a>
      </div>
    {% endblock %}
  </div>


</div>
</body>

</html>

templates/designTest/middle_design_test.html
{% extends "designTest/designTest.html" %}

{% block centercontent %}
  {% load staticfiles %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/middle_content_design.css' %}" />
  
  <!-- Left sidebar with links -->

  <div id="leftsidebar" class="leftsidebar" style="position: relative; top: 0px; height: 100%; left: 0px; width: 199px;">
   <img src="../../static/images/left_menu_long.jpg" style="position: relative; left: 0px; width: 199;"> 


    {% block leftsidebar %}
        {# <a href="{% url 'news.views.news' %}" class="menu">Novinky</a> </br></br></br> #}
	<a href="{% url 'news:news' 0 %}" class="menu" style="position: absolute; top: 170px; left: 65px;">Novinky</a> </br></br></br>
        <a href="{% url 'news.views.underConstruction' %}" class="menuNotActive" style="position: absolute; top: 225px; left: 65px;">Články&nbsp;&nbsp;</a> </br></br></br>
        {# <a href="{% url 'news.views.underConstruction' %}" class="menuNotActive">Blog&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</a> </br></br></br> #}
        <a href="{% url 'news.views.underConstruction' %}" class="menuNotActive" style="position: absolute; top: 275px; left: 65px;">Galerie&nbsp;&nbsp;</a> </br></br></br>
        <a href="{% url 'news.views.underConstruction' %}" class="menuNotActive" style="position: absolute; top: 330px; left: 65px;">Projekty</a> </br></br></br>
	<a href="{% url 'messages:messages' %}" class="menu" style="position: absolute; top: 385px; left: 65px;">Vzkazy&nbsp;&nbsp;&nbsp;</a> </br></br></br>

    {% endblock %}
  </div>

  <!-- Main content -->
  <div id="maincontent" class="centersidecontent" style="position: absolute; top: 0px; left: 199px; width: 870px; height: 100%;">
    <div id="maincontenttext" class="maincontenttext" style="position: absolute; top: 1%; left: 1%; width: 98%; height: 100%;">
      {% block maincontent %}
        <h2>MAIN CONTENT</h2>
      {% endblock %}
    </div>
  </div>


  <!-- Right sidebar block -->
 <div id="rightsidebar" class="rightsidebar" style="position: absolute; top: 0px; left: 1065px; width: 190px">

   <img src="../../static/images/right_menu_5.jpg" style="position: relative; left: 0px; width: 199;"> 

    {% block rightsidebar %}
      <div id="pictureofday" class="pictureofday" style="position: absolute; top: 2%; left: 2%">
        <a href="../underConstruction">Fotka dne, heslo dne ...</a>
	{{ content }}
      </div>
    {% endblock %}
   </div>


{% endblock %}

templates/designTest/news_design_test.html
{% extends "designTest/middle_design_test.html" %}


{% block maincontent %}


{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'news/news_style.css' %}" />

<br/>

        <font size="2px"><a href="{% url 'news:news' preview_start_id %}" title="10 předchozích novinek"><<</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</font>
	<font size="4px">Aktuality</font> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <font size="4px">Počet záznamů: {{ news_count }}</font> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font size="2px">Pro starší záznamy odrolujte dolu (po kliknutí myši do protřední sekce).</font>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font size="2px"><a href="{% url 'news:news' next_start_id %}" title="10 následujících novinek">>></a></font>
        
<br/>
<br/>

{% if news_list %}
    {% for new in news_list %}

	<div id="jednotlive_novinky" style="position: relative; float: down"> 

	<!-- Ramecek kolem jedne novinky -->
        <div id="new_item" style="position: relative; border: 1px solid gray;">

	  <!-- Mezera leva+prava textu od ramecku -->
	  <div id="left_space" style="position: relative; left: 1%; width: 98%;">

	    <br/>
            &nbsp;&nbsp;&nbsp; Title:&nbsp;&nbsp; <font size="6px">{{ new.title }}</font>  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Date:&nbsp;&nbsp; <font size="4px">{{ new.date }}</font>
	    <br/><br/>
            {{ new.text }}
        
            <br/><br/>
            <!-- Display links if they are available -->
            {% if new.link1 %}
              Odkaz 1:&nbsp;&nbsp; <a href="http://{{ new.link1 }}">{{ new.link1_name }}</a> </br> 
            {% endif  %}
            {% if new.link2 %}
              Odkaz 2:&nbsp;&nbsp; <a href="http://{{ new.link2 }}">{{ new.link2_name }}</a> </br>
            {% endif  %}
            {% if new.link3 %}
              Odkaz 3:&nbsp;&nbsp; <a href="http://{{ new.link3 }}">{{ new.link3_name }}</a> </br>
            {% endif  %}
            {% if new.link4 %} 
              Odkaz 4:&nbsp;&nbsp; <a href="http://{{ new.link4 }}">{{ new.link4_name }}</a> </br>
            {% endif  %}
	    <br/>

            <!-- Display pictures if they are available -->
	    <div id="obrazky" style="position: relative; width: 100%; height: 315px">

	      {% if new.image1 %}
		<div id="obr1" style="position: absolute; left: 1%">  
                  <img border="0" alt="" src="{{ new.image1.url }}" width="180px" style="border: 2px solid white; box-shadow: 0 0 2px rgba(0, 0, 0, 0.7);">
                  <br/>
		  {{ new.image1_name }}
		  <br/>
                  <a href="news_obr1_detail/{{ new.id }}">Zvětšit obrázek</a>
		</div>
              {% endif %}

              <!-- &nbsp;&nbsp;&nbsp;&nbsp; -->
              {% if new.image2 %}
		<div id="obr2" style="position: absolute; left: 26%;">
                  <img border="0" alt="" src="{{ new.image2.url }}" width="180px" style="border: 2px solid white; box-shadow: 0 0 2px rgba(0, 0, 0, 0.7);">
                  <br/>
		  {{ new.image2_name }}
		  </br>
                  <a href="news_obr2_detail/{{ new.id }}">Zvětšit Obrázek</a>
		</div>
              {% endif %}

              <!-- &nbsp;&nbsp;&nbsp;&nbsp; -->
              {% if new.image3 %}
		<div id="obr3" style="position: absolute; left: 51%;">
                  <img border="0" alt="" src="{{ new.image3.url }}" width="180px" style="border: 2px solid white; box-shadow: 0 0 2px rgba(0, 0, 0, 0.7);">
                  <br/>
		  {{ new.image3_name }}
		  <br/>
                  <a href="news_obr3_detail/{{ new.id }}">Zvětšit Obrázek</a>
		</div>
              {% endif %}

              <!-- &nbsp;&nbsp;&nbsp;&nbsp; -->
              {% if new.image4 %}
		<div id="obr4" style="position: absolute; left: 76%;">
                  <img border="0" alt="" src="{{ new.image4.url }}" width="180px" style="border: 2px solid white; box-shadow: 0 0 2px rgba(0, 0, 0, 0.7);">
                  <br/>
		  {{ new.image4_name }}
		  <br/>
                  <a href="news_obr4_detail/{{ new.id }}">Zvětšit Obrázek</a>
		</div>
              {% endif %}
	  
	    </div> <!-- Obrazky -->
	   
	    </div> <!-- Mezera -->

	    </div> <!-- Ramecek -->

	    <br/><br/>

	    </div> <!-- Jednotlive novinky -->	

    {% endfor %}

{% else %}
    <p>Žádné novinky nejsou k dispozici.</p>
{% endif %}

{% endblock %}


{% block rightsidebar %}
  <br/>
  <div id="PictureOfDay"  style="position: absolute; left: 5%; top: 5%;">
    Fotka týdne, heslo týdne ... 
    <br/><br/>

    {% if pictureOfWeek %}
      <img border="0" alt="" src="{{ pictureOfWeek.image.url }}" width="180px" style="border: 2px solid white; box-shadow: 0 0 2px rgba(0, 0, 0, 0.7);">
      <br/>
      <a href="{% url 'news:picture_of_week_detail' pictureOfWeek.id %}">{{ pictureOfWeek.title }}</a>
      <div id="hesloTydne" style="position: absolute; left: 0px; top: 220px">      
        <font size="2px">Heslo týdne:</font>
        <br>
        {{ pictureOfWeek.text }}       
      </div>
    {% else %}
      Žádný záznam pro foto týdne.
    {% endif%}

  </div>
{% endblock %}