news/urls.py
from django.conf.urls import patterns, include, url
from news import views

urlpatterns = patterns('',
    # Redirect to news/0/ ... last 10 news
    url(r'^$', views.news0_redirect, name='news0Redirect'),
    url(r'^(?P<start_id>\d+)/$', views.news, name='news'),
    url(r'^newsFromList/(?P<new_db_id>\d+)/$', views.newsFromList, name='newsFromList'),
    #url(r'^news/$', views.news, name='news'),    
    #url(r'^(?P<start_id>\d+)/news_obr1_detail/(?P<new_id>\d+)/$', views.obr1_detail, name='obr1_detail'),
    #url(r'^(?P<start_id>\d+)/news_obr2_detail/(?P<new_id>\d+)/$', views.obr2_detail, name='obr2_detail'),
    #url(r'^(?P<start_id>\d+)/news_obr3_detail/(?P<new_id>\d+)/$', views.obr3_detail, name='obr3_detail'),
    #url(r'^(?P<start_id>\d+)/news_obr4_detail/(?P<new_id>\d+)/$', views.obr4_detail, name='obr4_detail'),
    url(r'^(?P<start_id>\d+)/news_obr_detail/(?P<new_id>\d+)/(?P<obr_id>\d+)/$', views.obr_detail, name='obr_detail'),
    url(r'^pictureOfWeekDetail/(?P<picture_id>\d+)/$', views.picture_of_day_detail, name='picture_of_week_detail'),
    url(r'^info/$', views.info, name='info'),
    url(r'^kontakt/$', views.kontakt, name='kontakt'),
    url(r'^newsList/$', views.newsList, name='newsList'),
)

project_mysites/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static

from news import views

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'project_mysites.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('news.urls', namespace="news")),
    url(r'^messages/', include('messages.urls', namespace="messages")),
    #url(r'^article/', include('article.urls', namespace="article")),
    url(r'^underConstruction/', views.underConstruction, name='underConstruction'),
    url(r'^design/', views.designTest, name='designTest'),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

news/models.py
from django.db import models

# Create your models here.

class New(models.Model):
    title = models.CharField(max_length=80)
    date = models.DateTimeField(auto_now_add=True)
    text = models.CharField(max_length=1400)
    link1 = models.CharField(max_length=200, null=True, blank=True)
    link1_name = models.CharField(max_length=80, null=True, blank=True)
    link2 = models.CharField(max_length=200, null=True, blank=True)
    link2_name = models.CharField(max_length=80, null=True, blank=True)
    link3 = models.CharField(max_length=200, null=True, blank=True)
    link3_name = models.CharField(max_length=80, null=True, blank=True)
    link4 = models.CharField(max_length=200, null=True, blank=True)
    link4_name = models.CharField(max_length=80, null=True, blank=True)
    image1 = models.FileField(upload_to="images/", null=True, blank=True)
    image1_name = models.CharField(max_length=80, null=True, blank=True) 
    image2 = models.FileField(upload_to="images/", null=True, blank=True)
    image2_name = models.CharField(max_length=80, null=True, blank=True)
    image3 = models.FileField(upload_to="images/", null=True, blank=True)
    image3_name = models.CharField(max_length=80, null=True, blank=True)
    image4 = models.FileField(upload_to="images/", null=True, blank=True)
    image4_name = models.CharField(max_length=80, null=True, blank=True)
    

    def __unicode__(self):
        return self.title


class PhotoOfWeek(models.Model):
    title = models.CharField(max_length=80)
    image = models.FileField(upload_to="images/", null=True, blank=True)
    text = models.CharField(max_length=500)
    #date = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.title

news/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.http import HttpResponse

from news.models import New
from news.models import PhotoOfWeek

import string


# Create your views here. #

# More or less static views #################################################

def info(request):
    """Basic info about pages"""
    pictureOfWeek = PhotoOfWeek.objects.last()
    return render(request, 'news/info.html', {'pictureOfWeek': pictureOfWeek})


def kontakt(request):
    """Info about contatct of author"""
    pictureOfWeek = PhotoOfWeek.objects.last()
    return render(request, 'news/kontakt.html', {'pictureOfWeek': pictureOfWeek})


# More or less dynamic views #################################################

def news0_redirect(request):
    """Just redirect URL without parameters to the news/0/ ... the last 10 news"""
    return redirect('news:news', start_id='0')


def news(request, start_id):
    """Short news for info about latest actions"""

    MAX_NEWS = 10
    end_id = string.atoi(start_id) + 10

    news_count = New.objects.count()  # Pocet vsech zaznamu novinek
    news_list = New.objects.all().order_by("-date")[start_id:end_id]  # Sort by date ... and only part of list
    # misto vsech zaznamu ziskat jen ty v intervalu start - stop -> API

    # Vypocet prvniho ID z predchozi skupiny novinek (jedna skupina = MAX_NEWS) 
    start_id_num = string.atoi(start_id)
    if (start_id_num + MAX_NEWS) < news_count:
        preview_start_id = start_id_num + MAX_NEWS
    else:
        preview_start_id = start_id_num

    # Vypocet prvniho ID z nasledujici skupiny novinek (jedna skupina = MAX_NEWS) 
    next_start_id = start_id_num - MAX_NEWS  # prvni ID nasledujicich novinek
    if next_start_id < 0:
        next_start_id = 0;

    pictureOfWeek = PhotoOfWeek.objects.last()
    context = {'news_list': news_list, 'news_count': news_count, 'pictureOfWeek': pictureOfWeek, 'start_id': start_id,
               'preview_start_id': preview_start_id, 'next_start_id': next_start_id}
    return render(request, 'news/news.html', context)


def underConstruction(request):
    """General page to display that page is not finished"""
    pictureOfWeek = PhotoOfWeek.objects.last()
    return render(request, 'underConstruction.html', {'pictureOfWeek': pictureOfWeek})


# def obr1_detail(request, new_id, start_id):
#     """Show detail of picture"""
#     new = New.objects.get(pk=new_id)
#     pictureOfWeek = PhotoOfWeek.objects.last()
#     return render(request, 'news/obr1_detail.html', {'new': new, 'pictureOfWeek': pictureOfWeek, 'start_id': start_id})

# def obr2_detail(request, start_id):
#     """Show detail of picture"""
#     start_id_int = string.atoi(start_id)
#     new = New.objects.get(pk=start_id_int)
#     pictureOfWeek = PhotoOfWeek.objects.last()
#     return render(request, 'news/obr2_detail.html', {'new': new, 'pictureOfWeek': pictureOfWeek, 'start_id': start_id})

# def obr3_detail(request, new_id, start_id):
#     """Show detail of picture"""
#     new = New.objects.get(pk=new_id)
#     pictureOfWeek = PhotoOfWeek.objects.last()
#     return render(request, 'news/obr3_detail.html', {'new': new, 'pictureOfWeek': pictureOfWeek, 'start_id': start_id})

# def obr4_detail(request, new_id, start_id):
#     """Show detail of picture"""
#     new = New.objects.get(pk=new_id)
#     pictureOfWeek = PhotoOfWeek.objects.last()
#     return render(request, 'news/obr4_detail.html', {'new': new, 'pictureOfWeek': pictureOfWeek, 'start_id': start_id})


def obr_detail(request, new_id, start_id, obr_id):
    """
    Show detail of picture
    :param request:
    :param new_id:
    :param start_id:
    :return:
    """
    new = New.objects.get(pk=new_id)
    picture_of_week = PhotoOfWeek.objects.last()
    new_picture_id_list = __get_picture_id_list(new)
    requested_image = __get_requested_image(new, obr_id)
    previous_image = __get_previous_image_id(obr_id, new_picture_id_list)
    next_image = __get_next_image(obr_id, new_picture_id_list)

    parameters = {'new': new, 'pictureOfWeek': picture_of_week, 'start_id': start_id,
                  'requested_image': requested_image, 'previous_image': previous_image, 'next_image': next_image}

    return render(request, 'news/obr_detail.html', parameters)


def __get_picture_id_list(new):
    """
    Return list of ID images which are available for one specific new
    :param new:
    :return: list of images IDs which exists
    """
    id_list = []

    if new.image1:
        id_list.append(1)
    if new.image2:
        id_list.append(2)
    if new.image3:
        id_list.append(3)
    if new.image4:
        id_list.append(4)

    return id_list


def __get_requested_image(new, obr_id):
    """
    Return requested image
    :return:
    """
    # If picture doesn't exist link is not visible on page so don't have to verify if actual picture exists
    if obr_id == "1":
        requested_image = new.image1
    elif obr_id == "2":
        requested_image = new.image2
    elif obr_id == "3":
        requested_image = new.image3
    elif obr_id == "4":
        requested_image = new.image4
    else:
        requested_image = new.image1

    return requested_image


def __get_previous_image_id(obr_id, new_picture_id_list):
    """
    Return reguested image
    :return:
    """
    try:
        actual_id = int(obr_id)  # Exception ?
    except ValueError:
        actual_id = 0

    previous_id = None
    if actual_id - 1 <= 0:
        previous_id = new_picture_id_list[-1]  # Last in the list
    else:
        previous_id_flag = False  # True if next item in reversed list is next picture ID
        for id in reversed(new_picture_id_list):

            if previous_id_flag:  # next item in the reversed list is the previous picture id
                previous_id = id
                break

            if id == actual_id:  # This item is actual picture (next iteration is next picture ID)
                previous_id_flag = True

    return previous_id


def __get_next_image(obr_id, new_picture_id_list):
    """
    Return requested image
    :return:
    """
    try:
        actual_id = int(obr_id)  # Exception ?
    except ValueError:
        actual_id = 0

    next_id = None
    if actual_id >= len(new_picture_id_list):
        next_id = new_picture_id_list[0]  # First in the list
    else:
        next_id_flag = False  # True if next item in list is next picture ID
        for id in new_picture_id_list:

            if next_id_flag:  # next item in the list is the next picture id
                next_id = id
                break

            if id == actual_id:  # This item is actual picture (next iteration is next picture ID)
                next_id_flag = True

    return next_id


def picture_of_day_detail(request, picture_id):
    """Middle section loads picture of the day"""

    pictureBig = PhotoOfWeek.objects.get(pk=picture_id)  # big picture in the middle section (= picture for detail)
    pictureOfWeek = PhotoOfWeek.objects.last()  # small picture on the right panel (always the newest picture)

    all_pictures = PhotoOfWeek.objects.all().order_by("-id")
    temp_picture_id = 0
    count_pictures = len(all_pictures)
    for temp_picture in all_pictures:
        if temp_picture.id == string.atoi(picture_id):
            # Nalezeni predchozi fotky v poradi ##################
            if temp_picture_id < (count_pictures - 1):
                preview_picture = all_pictures[temp_picture_id + 1]
            else:
                preview_picture = all_pictures[count_pictures - 1]
            # Nalezeni nasledujici fotky v poradi ##################
            if temp_picture_id > 0:
                next_picture = all_pictures[temp_picture_id - 1]
            else:
                next_picture = all_pictures[0]

        # Na konci zvyseni indexu znamene presun indexu na starsi fotku (serazeno od nejnovejsi po nejstarsi ...order_by("-date")
        temp_picture_id += 1  # increase id for index in all_pictures array
        # End of for cyklus

    content = {'picture': pictureBig, 'preview_picture_id': preview_picture.id, 'next_picture_id': next_picture.id,
               'pictureOfWeek': pictureOfWeek, }
    return render(request, 'news/picture_of_day.html', content)


def newsList(request):
    """List of all news"""

    news_count = New.objects.count()  # Pocet vsech zaznamu novinek
    news_list = New.objects.all().order_by("date")  # Sort by date ... and only part of list
    # misto vsech zaznamu ziskat jen ty v intervalu start - stop -> API

    pictureOfWeek = PhotoOfWeek.objects.last()
    context = {'news_list': news_list, 'news_count': news_count, 'pictureOfWeek': pictureOfWeek}
    return render(request, 'news/newsList.html', context)


def newsFromList(request, new_db_id):
    """News acording new_db_id (database ID of new)"""
    MAX_NEWS = 10

    news_count = New.objects.count()  # Pocet vsech zaznamu novinek
    news_list_all = New.objects.all().order_by("-date")  # Sort by date ...
    # Z celeho seznamu novinek vybereme jen 10 zacinajici pozadovanym 'new_db_id'
    news_list_part = []
    start_index = 0;
    new_db_id_num = string.atoi(new_db_id)
    for new in news_list_all:
        if new.id == new_db_id_num:
            news_list_part = news_list_all[start_index:start_index + MAX_NEWS]
            break
        start_index = start_index + 1

    # Vypocet prvniho ID z predchozi skupiny novinek (jedna skupina = MAX_NEWS)
    # Poradi je otocene! Posledne zadana novinka je prvni v poradi
    if (start_index + MAX_NEWS) < news_count:
        preview_start_id = start_index + MAX_NEWS
    else:
        preview_start_id = start_index

    # Vypocet prvniho ID z nasledujici skupiny novinek (jedna skupina = MAX_NEWS)
    # Poradi je otocene! Posledne zadana novinka je prvni v poradi
    next_start_id = start_index - MAX_NEWS  # prvni ID nasledujicich novinek
    if next_start_id < 0:
        next_start_id = 0;

templates/news/info.html
{% extends "news/news.html" %}


{% block maincontent %}

  <div id="maincontenttext" class="maincontenttext" style="position: absolute; top: 1%; left: 3%; hight: 100%; width: 90%">

    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'news/style.css' %}" />

    <h2>O čem to tu je ?</h2>
    Stránky vznikly ze dvou hlavních důvodů:
    <ol>
      <li>
        Mít možnost dát vědět, kde se zrovna nacházime na našich cestách a prezentovat nějakou tu fotku nebo postřeh na který bych brzo zapoměl.
      </li>
      <li>
        Otestovat a naučit se práci s webovým frameworkem Django
      </li>
      <li>
        Zabavit se před odjezdem do Indie a na Nový Zéland :-)
      </li>
    </ol>

    <h3>Stránky vznikly během pár večerů a zatím NEJSOU dodělané, optimalizované a odladěné. Pro začátek jsou v provozu pouze novinky a foto týdne. Další části přibydou snad později, pokud na ně bude čas (snad ano ...).</h3>

    <br/><br/><br/>

    <h4>Připomínky a kontakt:</h4> 
    <a href="mailto: michalbroucek@seznam.cz?subject=Vzkaz z: mbrouk.cz"><b>michalbroucek@seznam.cz</b></a>
    <br/><br/><br/>
    <h3>Děkuji za pochopení </h3>
  </div>

{% endblock %}

templates/news/kontakt.html
{% extends "news/news.html" %}


{% block maincontent %}

  <div id="maincontenttext" class="maincontenttext" style="position: absolute; top: 1%; left: 3%; hight: 100%; width: 90%">

    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'news/style.css' %}" />

    <h2>Kdo bude mít zájem, může použít kontakty níže. Odpověď můžete očekávat do měsíce :-)</h2>

    <h3>Mobil: +420 602 452073</h3>
    <h3>Mail 1: <a href="mailto: michalbroucek@seznam.cz?subject=Vzkaz z: mbrouk.cz"><b>michalbroucek@seznam.cz</b></a></h3>
    <h3>Mail 2: <a href="mailto: michalbroucek@gmail.com?subject=Vzkaz z: mbrouk.cz"><b>michalbroucek@gmail.com</b></a></h3>

  </div>

{% endblock %}

templates/news/news.html
{% extends "middle_content.html" %}


{% block maincontent %}


{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'news/news_style.css' %}" />

<br/>

    <font size="2px"><a href="{% url 'news:news' preview_start_id %}" title="10 předchozích novinek"><<</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</font>
	<font size="4px">Aktuality</font> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <font size="4px">Počet záznamů: {{ news_count }}</font> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <a href="{% url 'news:newsList' %}">Seznam novinek</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font size="2px"><a href="{% url 'news:news' next_start_id %}" title="10 následujících novinek">>></a></font>
        
<br/>
<br/>

{% if news_list %}
    {% for new in news_list %}

	<div id="jednotlive_novinky" style="position: relative; float: down"> 

	<!-- Ramecek kolem jedne novinky -->
    <div id="new_item" style="position: relative; border: 1px solid gray;">

	  <!-- Mezera leva+prava textu od ramecku -->
	  <div id="left_space" style="position: relative; left: 1%; width: 98%;">
        <br/>
        &nbsp;&nbsp;&nbsp; Title:&nbsp;&nbsp; <font size="6px">{{ new.title }}</font>  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Date:&nbsp;&nbsp; <font size="4px">{{ new.date }}</font>
	    <br/><br/>
        {{ new.text }}
        
        <br/><br/>
        <!-- Display links if they are available -->
        {% if new.link1 %}
          Odkaz 1:&nbsp;&nbsp; <a href="http://{{ new.link1 }}">{{ new.link1_name }}</a> </br>
        {% endif  %}
        {% if new.link2 %}
          Odkaz 2:&nbsp;&nbsp; <a href="http://{{ new.link2 }}">{{ new.link2_name }}</a> </br>
        {% endif  %}
        {% if new.link3 %}
          Odkaz 3:&nbsp;&nbsp; <a href="http://{{ new.link3 }}">{{ new.link3_name }}</a> </br>
        {% endif  %}
        {% if new.link4 %}
          Odkaz 4:&nbsp;&nbsp; <a href="http://{{ new.link4 }}">{{ new.link4_name }}</a> </br>
        {% endif  %}
	    <br/>

        <!-- Display pictures if they are available -->
	    <div id="obrazky" style="position: relative; width: 100%; height: 315px">

        {% if new.image1 %}
		    <div id="obr1" style="position: absolute; left: 1%">
                <img border="0" alt="" src="{{ new.image1.url }}" width="190" style="border: 2px solid white; box-shadow: 0 0 2px rgba(0, 0, 0, 0.7);">
                <br/>
                {{ new.image1_name }}
		        <br/>
                <a href="{% url 'news:obr_detail' start_id new.id 1 %}">Zvětšit obrázek</a>
		    </div>
        {% endif %}

        <!-- &nbsp;&nbsp;&nbsp;&nbsp; -->
        {% if new.image2 %}
		    <div id="obr2" style="position: absolute; left: 26%;">
                <img border="0" alt="" src="{{ new.image2.url }}" width="190" style="border: 2px solid white; box-shadow: 0 0 2px rgba(0, 0, 0, 0.7);">
                <br/>
		        {{ new.image2_name }}
		        </br>
                <!-- <a href="news_obr_detail/{{ new.id }}/2">Zvětšit obrázek</a> -->
                <a href="{% url 'news:obr_detail' start_id new.id 2 %}">Zvětšit obrázek</a>
		    </div>
        {% endif %}

        <!-- &nbsp;&nbsp;&nbsp;&nbsp; -->
        {% if new.image3 %}
		    <div id="obr3" style="position: absolute; left: 51%;">
                <img border="0" alt="" src="{{ new.image3.url }}" width="190" style="border: 2px solid white; box-shadow: 0 0 2px rgba(0, 0, 0, 0.7);">
                <br/>
		        {{ new.image3_name }}
		        <br/>
                <a href="news_obr_detail/{{ new.id }}/3">Zvětšit obrázek</a>
		    </div>
        {% endif %}

        <!-- &nbsp;&nbsp;&nbsp;&nbsp; -->
        {% if new.image4 %}
		    <div id="obr4" style="position: absolute; left: 76%;">
                <img border="0" alt="" src="{{ new.image4.url }}" width="190" style="border: 2px solid white; box-shadow: 0 0 2px rgba(0, 0, 0, 0.7);">
                <br/>
		        {{ new.image4_name }}
		        <br/>
                <a href="news_obr_detail/{{ new.id }}/4">Zvětšit obrázek</a>
		    </div>
        {% endif %}
	  
	    </div> <!-- Obrazky -->
	   
	    </div> <!-- Mezera -->

	    </div> <!-- Ramecek -->

	    <br/><br/>

	    </div> <!-- Jednotlive novinky -->	

    {% endfor %}


{% else %}
    <p>Žádné novinky nejsou k dispozici.</p>
{% endif %}

{% endblock %}


{% block rightsidebar %}
  <br/>
  <div id="PictureOfDay" style="position: absolute; left: 10px; top: 20px;">
    Fotka týdne, heslo týdne ... 
    <br/><br/>

    {% if pictureOfWeek %}
      <img border="0" alt="" src="{{ pictureOfWeek.image.url }}" width="170px" style="border: 2px solid white; box-shadow: 0 0 2px rgba(0, 0, 0, 0.7);">
      <br/>
      <a href="{% url 'news:picture_of_week_detail' pictureOfWeek.id %}">{{ pictureOfWeek.title }}</a>
      <div id="hesloTydne" style="position: absolute; left: 0px; top: 220px;">      
        <font size="2px">Heslo týdne:</font>
        <br>
        {{ pictureOfWeek.text }}       
      </div>
    {% else %}
      Žádný záznam pro foto týdne.
    {% endif%}

  </div>
{% endblock %}

templates/news/newsList.html
{% extends "middle_content.html" %}


{% block maincontent %}

  {% load staticfiles %}
  <link rel="stylesheet" type="text/css" href="{% static 'news/news_style.css' %}" />

  <!-- Mezera leva+prava textu od okraje -->
  <div id="left_space" style="position: relative; left: 5%; width: 90%;">

  <br/>
	<font size="5px">Seznam vsech novinek</font>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <font size="4px">Počet záznamů: {{ news_count }}</font>
  <br/>
  <br/>

  {% if news_list %}
      <ol>
      {% for new in news_list %}
	  <li>
	  <a href="/newsFromList/{{ new.id }}">{{ new.title }}</a>
	  </li>
      {% endfor %}
      </ol>
  {% else %}
      <p>Žádné novinky nejsou k dispozici.</p>
  {% endif %}

  </div>
{% endblock %}

{% block rightsidebar %}
  <br/>
  <div id="PictureOfDay" style="position: absolute; left: 10px; top: 20px;">
    Fotka týdne, heslo týdne ... 
    <br/><br/>

    {% if pictureOfWeek %}
      <img border="0" alt="" src="{{ pictureOfWeek.image.url }}" width="170px" style="border: 2px solid white; box-shadow: 0 0 2px rgba(0, 0, 0, 0.7);">
      <br/>
      <a href="{% url 'news:picture_of_week_detail' pictureOfWeek.id %}">{{ pictureOfWeek.title }}</a>
      <div id="hesloTydne" style="position: absolute; left: 0px; top: 220px;">      
        <font size="2px">Heslo týdne:</font>
        <br>
        {{ pictureOfWeek.text }}       
      </div>
    {% else %}
      Žádný záznam pro foto týdne.
    {% endif%}

  </div>
{% endblock %}

templates/news/obr1_detail.html
{% extends "news/news.html" %}


{% block maincontent %}

  {% load staticfiles %}
  <link rel="stylesheet" type="text/css" href="{% static 'news/news_style.css' %}" />
 
  <!-- Back to the news/ page -->
  <div id="zpet" style="position: absolute; top: 0%; left: 0%;">
    <a href="{% url 'news:news' start_id %}">&crarr; Zpět</a>
  </div>

  <div id=obr_detail style="position: absolute; top: 0%; left: 7%;">
    <!--TODO move individual templates for image1-4 detail into one -> make it more general when have time -->
    <img border="0" alt="" src="{{ new.image1.url }}" width="770px" hight="577px" style="border: 4px solid white; box-shadow: 0 0 2px rgba(0, 0, 0, 0.7);">
  </div>

{% endblock %}

templates/news/obr_detail.html
{% extends "news/news.html" %}

{% block maincontent %}

    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'news/news_style.css' %}" />

    <div id=obr_detail style="position: absolute; top: 0%; left: 2%;">

    <!-- Back to the news/ page -->

        <a href="{% url 'news:news' start_id %}">&#8617; Zpět</a>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <a href="{% url 'news:obr_detail' start_id new.id previous_image %}">&#x27FB; Předchozí obr.</a>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <a href="{% url 'news:obr_detail' start_id new.id next_image %}">Další obr. &#x27FC;</a>

        <br/><br/>
        <img border="0" alt="" src="{{ requested_image.url }}" width="800px" hight="600px" style="border: 4px solid white; box-shadow: 0 0 2px rgba(0, 0, 0, 0.7);">
    </div>

{% endblock %}

templates/news/picture_of_day.html
{% extends "news/news.html" %}

{% block maincontent %}

  {% load staticfiles %}
  <link rel="stylesheet" type="text/css" href="{% static 'news/news_style.css' %}" />

  <!-- Back to the news/ page link, previous photo and next photo links -->
  <div id=zpet style="position: absolute; top: 0%; left: 0%">
    <a href="{% url 'news:news' 0 %}">&crarr; Zpět</a> </br></br></br></br>  
    <a href="{% url 'news:picture_of_week_detail' preview_picture_id %}" title="Předchozí fotka týdne"><<</a> </br> <font size="2px">Předchozí</br>fotka</font>  </br></br>
    <a href="{% url 'news:picture_of_week_detail' next_picture_id %}" title="Následující fotka týdne">>></a> </br> <font size="2px">Následující</br>fotka</font>  </br> 
    </br>
    </br>
  </div>

  <div id=obr_detail style="position: absolute; top: 0%; left: 8%">
    <!--TODO move individual templates for image1-4 detail into one -> make it more general when have time -->
    <img border="0" alt="" src="{{ picture.image.url }}" width="770px" hight="577px" style="border: 4px solid white; box-shadow: 0 0 2px rgba(0, 0, 0, 0.7);">

    <br/><br/>

    Heslo týdne:
    <br/><br/>
    {{ picture.text }}

  </div>

{% endblock %}