messages/urls.py
from django.conf.urls import patterns, include, url
from messages import views

urlpatterns = patterns('',
    url(r'^$', views.messages, name='messages'),
    url(r'^new/$', views.new_message, name='new_message'),
    url(r'^receive_message/$', views.receive_message, name='receive_message'),
)

news/urls.py
from django.conf.urls import patterns, include, url
from news import views

urlpatterns = patterns('',
    # Redirect to news/0/ ... last 10 news
    url(r'^$', views.news0_redirect, name='news0Redirect'),
    url(r'^(?P<start_id>\d+)/$', views.news, name='news'),
    url(r'^newsFromList/(?P<new_db_id>\d+)/$', views.newsFromList, name='newsFromList'),
    #url(r'^news/$', views.news, name='news'),    
    #url(r'^(?P<start_id>\d+)/news_obr1_detail/(?P<new_id>\d+)/$', views.obr1_detail, name='obr1_detail'),
    #url(r'^(?P<start_id>\d+)/news_obr2_detail/(?P<new_id>\d+)/$', views.obr2_detail, name='obr2_detail'),
    #url(r'^(?P<start_id>\d+)/news_obr3_detail/(?P<new_id>\d+)/$', views.obr3_detail, name='obr3_detail'),
    #url(r'^(?P<start_id>\d+)/news_obr4_detail/(?P<new_id>\d+)/$', views.obr4_detail, name='obr4_detail'),
    url(r'^(?P<start_id>\d+)/news_obr_detail/(?P<new_id>\d+)/(?P<obr_id>\d+)/$', views.obr_detail, name='obr_detail'),
    url(r'^pictureOfWeekDetail/(?P<picture_id>\d+)/$', views.picture_of_day_detail, name='picture_of_week_detail'),
    url(r'^info/$', views.info, name='info'),
    url(r'^kontakt/$', views.kontakt, name='kontakt'),
    url(r'^newsList/$', views.newsList, name='newsList'),
)

project_mysites/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static

from news import views

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'project_mysites.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('news.urls', namespace="news")),
    url(r'^messages/', include('messages.urls', namespace="messages")),
    #url(r'^article/', include('article.urls', namespace="article")),
    url(r'^underConstruction/', views.underConstruction, name='underConstruction'),
    url(r'^design/', views.designTest, name='designTest'),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

messages/models.py
from django.db import models

# Create your models here.

class Message(models.Model):
    title = models.CharField(max_length=80)
    author = models.CharField(max_length=80, null=True, blank=True)
    mail = models.CharField(max_length=120, null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    text = models.CharField(max_length=1400)
    
    def __unicode__(self):
        return self.title

messages/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.utils import timezone

from messages.models import Message

# Create your views here.

def messages(request):
    """List of messages which were stored by visitors."""
    messages = Message.objects.all().order_by("-date")
    count_messages = len(messages)
    # List of messages only for displaying History on the right-side panel - last 7 comments only
    message_history = messages[:7]
    content = {'messages': messages, 'count_messages': count_messages, 'message_history': message_history}
    return render(request, 'messages/messages.html', content)


def new_message(request):
    """Add new message via form page"""
    messages = Message.objects.all().order_by("-date")
    count_messages = len(messages)
    # List of messages only for displaying History on the right-side panel - last 7 comments only
    message_history = messages[:7]
    content = {'messages': messages, 'count_messages': count_messages, 'message_history': message_history} 
    return render(request, 'messages/new_message.html', content)


def receive_message(request):
    """Receive message from FORM which add new message."""

    # Just for data inside right panel = History
    messages = Message.objects.all().order_by("-date")
    count_messages = len(messages)
    # List of messages only for displaying History on the right-side panel - last 7 comments only
    message_history = messages[:7]
    content = {'messages': messages, 'count_messages': count_messages, 'message_history': message_history} 

    # Values receive from Form
    title_value = ""
    text_value = ""
    author_value = ""
    mail_value = ""
    # These values has to be sent from form and needs to be not empty string
    mandatory_form_values = {'title': False, 'text': False}

    # TITLE:
    # Get 'title' from the form data or set flag (mandatory_form_values) for sending data again if title is empty string
    try:
        # Get title from sent Form
        title_value = request.POST['title']
	# Check if title isn't empty string and if yes then redirect to form again - should be pre-prepared form from preview values
	if len(title_value) == 0:
            mandatory_form_values['title'] = False
        else:
            mandatory_form_values['title'] = True
    except (KeyError):
        # Error: missing value 'title' from Form data
        content['error_message'] = "Chybi interni polozka 'Nadpis' z odeslaneho formulare !"
        return render(request, 'messages/new_message.html', content)

    # TEXT:
    # Get 'text' from the Form data or set flag (mandatory_from_values) for sending data again if text is empty string
    try:
        # Get text from sent form
        text_value = request.POST['text']
        # Check if text isn't empty string and if yes then redirect to form again - should be pre-prepared form from preview values
        if len(text_value) == 0:
            mandatory_form_values['text'] = False
        else:
            mandatory_form_values['text'] = True
    except (KeyError):
        # Error: missing value 'text' from Form data
        content['error_message'] = "Chybi interni polozka 'Text' z odelsaneho formulare !"
        return render(request, 'messages/new_message.html', content)

    # AUTHOR:
    # Get 'author' from the Form data or redirect to clear form again if there is a error
    try:
        # Get mail from sent form
        author_value = request.POST['author']
    except (KeyError):
        # Error: missing value 'mail' from Form data
        content['error_message'] = "Chybi interni polozka 'Autor' z odeslaneho formulare !"
        return render(request, 'messages/new_message.html', content)

    # MAIL:
    # Get 'mail' from the Form data or redirect to the clear form again if there is a error
    try:
        # Get mail from sent form
        mail_value = request.POST['mail']
    except (KeyError):
        # Error: missing value 'mail' from Form data
        content['error_message'] = "Chybi interni polozka 'Mail' z odeslaneho formulare !"
        return render(request, 'messages/new_message.html', content)

    content['title_value'] = title_value 
    content['author_value'] = author_value
    content['mail_value'] = mail_value
    content['text_value'] = text_value
    # Test if mandatory values (title and text) were receive correctly if not then redirect to form again
    if ((mandatory_form_values['title'] == False) and (mandatory_form_values['text'] == False)):
        # Mistake - Both 'title' and 'text' content are missing
        content['error_message'] = "Chybi povinne polozky 'Nadpis' a 'Text' ve formulari !"
        return render(request, 'messages/new_message.html', content)
    elif mandatory_form_values['title'] == False:
        # Mistake - item 'title' is missting (empty)
        content['error_message'] = "Zapomel jsi vyplnit 'Nadpis' ve formulari !'"
        return render(request, 'messages/new_message.html', content)
    elif mandatory_form_values['text'] == False:
        # Mistake - item 'text' is missing (empty)
        content['error_message'] = "Zapomel jsi vyplnit 'Text' ve formulari !"
        return render(request, 'messages/new_message.html', content)
    else:
        # Zpracovat formular
	# Vytvorit novou message a ulozit ji do DB
	# return HttpResponseRedirect
        comment = Message(title=title_value, author=author_value, mail=mail_value, text=text_value, date=timezone.now())
        comment.save()
        #return render(request, 'messages/receive_message.html', content)
        # Redirect to the list of existing messages
        return HttpResponseRedirect(reverse('messages:messages'))

templates/messages/messages.html
{% extends "middle_content.html" %}

{% block maincontent %}

<br/>
&nbsp;&nbsp;&nbsp;&nbsp; Vzkazy (počet celkem: {{ count_messages }})&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; <a href="{% url 'messages:new_message' %}"> <b>Vložit nový vzkaz</b> </a> &nbsp;&nbsp;&nbsp;&nbsp;
<br/><br/>

{% if messages %}

    {% for message in messages %}
        <div id="jedna_zprava_ramecek" style="position: relative; border: 1px solid gray;">
            <div id="mezera_od_ramecku" style="position: relative; left: 1%; width: 98%;">
                <font size="5px" style="color: gray"> <b> {{ message.title }} </b> </font> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  	        <font size="2px">Datum:</font> {{ message.date }} &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <font size="2px">Autor:</font> <font style="color: gray"><b>{{ message.author }}</b></font> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <font size="2px">Email:</font> <a href="">{{ message.mail }}</a> 
                <br/>
	        <br/>
	        {{ message.text }}
            </div> {# konec div mezery od ramecku #} 
            <br/>
        </div>  {# konec div ramecku #}
        <br/><br/>
    {% endfor %}

{% else %}
    <p>Žádné vzkazy nejsou k dispozici.</p>
{% endif %}

{% endblock %} {# end block maincontent #}


{% block rightsidebar %}
    <div id="rightPanelContent" style="position: absolute; left: 5%; top: 50px">

    <h3>Historie: </h3>
    
    {% for message in message_history %}
        {{ message.date }}<br/>
        <font style="color: gray">{{ message.title }}</font>
        <br/><br/>
    {% endfor %}

    </div>
{% endblock %}

templates/messages/new_message.html
{% extends "messages/messages.html" %}

{% block maincontent %}
    <h2>Vytvoř a odešli nový vzkaz</h2>
    <br/>
    {% if error_message %}

        {# Formular se nacita znovu - protoze nebyly vyplneny vsechny povinne polozky, nacitame hodnoty jiz jednou zadane uzivatelem #} 
        <p><strong><font color=red>{{ error_message }}</font></strong></p>

        {# Zobrazit jiz pred-vyplneny formular! - mozna by stacila jedna definice pro oba #} 
        <form action="{% url 'messages:receive_message' %}" method="post">
        {% csrf_token %}

	    {# Test CSS pro form input #}
            <style>
            <!--
            input {background-color: #000000; color: #FFFFFF; font-size: 12pt}
            -->
            </style>

            <label for="title">Nadpis:&nbsp;</label>
            <input type="text" maxlength="80" size="50" name="title" id="title" value="{{ title_value }}" /> <br/><br/>
            <label for="author">Autor:&nbsp;&nbsp;</label>
            <input type="text" maxlength="80" size="50" name="author" id="author" value="{{ author_value }}" /> <br/><br/>
            <label for="mail">Email:&nbsp;&nbsp;</label>
            <input type="text" maxlength="120" size="50" name="mail" id="mail" value="{{ mail_value }}" /> <br/><br/><br/>
            <label for="title">Text:&nbsp;&nbsp;</label> <br/>
            <textarea cols="100" rows="6" name="text" id="text" maxlength="1400" style="background-color: #000000; color: #FFFFFF; font-size: 10pt">{{ text_value }}</textarea> <br/><br/>

            <input type="submit" value="Odeslat" />
        </form>
 
    {% else %}

        <form action="{% url 'messages:receive_message' %}" method="post">
        {% csrf_token %}

	    {# Test CSS pro form input #}
            <style>
            <!--
            input {background-color: #000000; color: #FFFFFF; font-size: 12pt}
            -->
            </style>

            <label for="title">Nadpis:&nbsp;</label>
            <input type="text" maxlength="80" size="50" name="title" id="title" /> <br/><br/>
            <label for="author">Autor:&nbsp;&nbsp;</label>
            <input type="text" maxlength="80" size="50" name="author" id="author" value="" /> <br/><br/>
            <label for="mail">Email:&nbsp;&nbsp;</label>
            <input type="text" maxlength="120" size="50" name="mail" id="mail" value="" /> <br/><br/><br/>
            <label for="title">Text:&nbsp;&nbsp;</label> <br/>
            <textarea cols="100" rows="6" name="text" id="text" maxlength="1400" style="background-color: #000000; color: #FFFFFF; font-size: 10pt"></textarea> <br/><br/>

            <input type="submit" value="  Odeslat formulář  " />
        </form>

    {% endif %}

{% endblock %}


{% block rightsidebar %}
    <div id="rightPanelContent" style="position: absolute; left: 5%; top: 50px">
        <h3>Historie: </h3>

        {% for message in message_history %}
            {{ message.date }} <br/>
            <font style="color: gray">{{ message.title }}</font>
            <br/><br/>
        {% endfor %}
    </div>
{% endblock %}

templates/messages/receive_message.html
{% extends "messages/messages.html" %}

{% block maincontent %}
    <h1>Odeslano ... zatim fake</h1>
    <h2>Text: {{ title }}</h2>
    <h3>Size: {{ title_size }}<h3>
{% endblock %}

{% block rightsidebar %}
    <h1>TODO</h1>
{% endblock %}